name: Build and push docker image to docker hub

on:
  push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASS}}
      
      
      - name: Setup Docker Buildx in github action runner
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with: 
          # Setting push to true ensures that the built image is pushed to the Docker registry.
          push: true
          # specifies how the Docker image will be tagged in the Docker registry.
          # username/reponame where image will be built
          tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

